export const proyectos = [
    {
        name: "Blog de Recetas",
        desc: "",
        repo: "https://github.com/cacho-medina/blog-de-recetas",
        url: "https://blog-de-recetas.vercel.app/",
        img: "./src/assets/recetas.jpg",
    },
    {
        name: "Web de noticias",
        desc: "",
        repo: "https://github.com/cacho-medina/web-noticias",
        url: "https://web-noticias-rc.netlify.app/",
        img: "./src/assets/noticia.jpg",
    },
    {
        name: "Reservas de veterinaria",
        desc: "",
        repo: "https://github.com/cacho-medina/reservas-veterinaria",
        url: "https://reservas-veterinaria.netlify.app/",
        img: "./src/assets/veterinaria.jpg",
    },
    {
        name: "Estudio Guzman",
        desc: "",
        repo: "https://github.com/cacho-medina/estudio-guzman",
        url: "https://guzmanabogados.com.ar/",
        img: "./src/assets/abogado.jpg",
    },
    {
        name: "Trendy Shop",
        desc: "",
        repo: "https://github.com/Henry-PF/ecommerce-admin",
        url: "https://www.youtube.com/watch?v=H1kmQmUvA4E&t=1s",
        img: "./src/assets/trendy.png",
    },
    {
        name: "Anime Heaven",
        desc: "",
        repo: "",
        url: "https://animeheaven-nim.netlify.app/",
        img: "./src/assets/anime.png",
    },
    {
        name: "R-parrillada",
        desc: "",
        repo: "https://github.com/cacho-medina/R-parrillada",
        url: "https://r-parrillada.vercel.app/",
        img: "./src/assets/parrilla.png",
    },
    {
        name: "Conferencias Buenos Aires",
        desc: "",
        repo: "https://github.com/cacho-medina/proyecto-final-cac",
        url: "https://www.youtube.com/watch?v=LNB4lHHNFQA&t=86s",
        img: "./src/assets/ba.jpg",
    },
    {
        name: "Rolling Soft",
        desc: "",
        repo: "https://github.com/mauroarms/Proyecto2_RC_MSFTGames",
        url: "https://rollingsoft.netlify.app/",
        img: "./src/assets/eafc.jpg",
    },
];
