export const proyectos = [
    {
        name: "Rolling Coffee",
        desc: "Proyecto para registrar productos de una cafeteria. (Aun en desarrollo)",
        repo: "https://github.com/cacho-medina/rolling-coffee",
        url: "https://rolling-coffee.netlify.app/",
        img: "./src/assets/recetas.jpg",
    },
    {
        name: "Blog de Recetas",
        desc: "Proyecto en el que podes registrar y visualizar tus recetas favoritas. (Aun en desarrollo)",
        repo: "https://github.com/cacho-medina/blog-de-recetas",
        url: "https://blog-de-recetas.vercel.app/",
        img: "./src/assets/recetas.jpg",
    },
    {
        name: "Conferencias Buenos Aires",
        desc: "Proyecto fullstack para administrar el registro de oradores y espectadores para conferencia en Buenos Aires",
        repo: "https://github.com/cacho-medina/proyecto-final-cac",
        url: "https://www.youtube.com/watch?v=LNB4lHHNFQA&t=86s",
        img: "./src/assets/ba.jpg",
    },
    {
        name: "Trendy Shop",
        desc: "Trendy Shop es un proyecto de una tienda virtual donde podés navegar a través de los productos en tendencia o buscarlos según su categorí",
        repo: "https://github.com/Henry-PF/ecommerce-admin",
        url: "https://www.youtube.com/watch?v=H1kmQmUvA4E&t=1s",
        img: "./src/assets/trendy.png",
    },
    {
        name: "Web de noticias",
        desc: "Aplicacion de noticias en la que podemos visualizar las ultimas noticias sobre los temas más importantes en la actualidad sobre nuestro pais y el mundo",
        repo: "https://github.com/cacho-medina/web-noticias",
        url: "https://web-noticias-rc.netlify.app/",
        img: "./src/assets/noticia.jpg",
    },
    {
        name: "Reservas de veterinaria",
        desc: "Proyecto para gestionar reservas de una veterinaria",
        repo: "https://github.com/cacho-medina/reservas-veterinaria",
        url: "https://reservas-veterinaria.netlify.app/",
        img: "./src/assets/veterinaria.jpg",
    },
    {
        name: "Estudio Guzman",
        desc: "Pagina para importante estudio de abogados",
        repo: "https://github.com/cacho-medina/estudio-guzman",
        url: "https://guzmanabogados.com.ar/",
        img: "./src/assets/abogado.jpg",
    },
    {
        name: "Anime Heaven",
        desc: "Anime Heaven es una tienda online diseñada para los fanáticos del anime",
        repo: "",
        url: "https://animeheaven-nim.netlify.app/",
        img: "./src/assets/anime.png",
    },
    {
        name: "R-parrillada",
        desc: "R-parrillada es una página donde se muestra información sobre un restaurante y sus prestaciones",
        repo: "https://github.com/cacho-medina/R-parrillada",
        url: "https://r-parrillada.vercel.app/",
        img: "./src/assets/parrilla.png",
    },

    {
        name: "Rolling Soft",
        desc: "Rolling Soft es una tienda online donde podes encontrar tus juegos favoritos a un precio de locos",
        repo: "https://github.com/mauroarms/Proyecto2_RC_MSFTGames",
        url: "https://rollingsoft.netlify.app/",
        img: "./src/assets/eafc.jpg",
    },
];
